---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-home-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-home-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-home-int-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_INTERNAL}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-home-int-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_INTERNAL}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-work-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_WORK}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-work-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - "${SECRET_DOMAIN_WORK}"
