---
clusterName: test-cluster
talosVersion: v1.3.5
kubernetesVersion: v1.26.0
endpoint: https://${clusterEndpointIP}:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
  #name: custom
  #urls:
  #  - https://raw.githubusercontent.com/Ramblurr/home-lab/main/talos/cilium/quick-install.yaml
additionalApiServerCertSans:
  - ${clusterEndpointIP}
additionalMachineCertSans:
  - ${clusterEndpointIP}
  - test-cluster.int.socozy.casa
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
nodes:
  - hostname: kmaster0-test.int.socozy.casa
    disableSearchDomain: true
    ipAddress: 192.168.1.104
    installDiskSelector:
      size: ">= 99GB"
    controlPlane: true
    nodeLabels:
      env: test
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.9.4.4
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.104/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: ${clusterEndpointIP}

  - hostname: kmaster1-test.int.socozy.casa
    disableSearchDomain: true
    ipAddress: 192.168.1.106
    installDiskSelector:
      size: ">= 99GB"
    controlPlane: true
    nodeLabels:
      env: test
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.9.4.4
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.106/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: ${clusterEndpointIP}

  - hostname: kmaster2-test.int.socozy.casa
    disableSearchDomain: true
    ipAddress: 192.168.1.107
    installDiskSelector:
      size: ">= 99GB"
    controlPlane: true
    nodeLabels:
      env: test
    kernelModules:
      - name: br_netfilter
        parameters:
          - nf_conntrack_max=131072
    nameservers:
      - 10.9.4.4
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.107/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: ${clusterEndpointIP}

controlPlane:
  patches:
    #- |-
    #  - op: add
    #    path: /cluster/apiServer/admissionControl/0/configuration/exemptions
    #    value:
    #      namespaces:
    #        - kube-system
    #        - cilium-test
    #        - rook-ceph
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - time.cloudflare.com
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - test-cluster.int.socozy.casa
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,CronJobTimeZone=true
            rotate-server-certificates: "false"
            #rotate-server-certificates: "true"
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false,CronJobTimeZone=true
          rotate-server-certificates: "false"
          #rotate-server-certificates: "true"
    - |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com
