---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - bjw-s.yaml
  - coredns-charts.yaml
  - external-dns.yaml
  - kustomization.yaml
  - metrics-server-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - weave-gitops.yaml
  - cilium-charts.yaml
